services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

  prometheus:
    extends:
      file: .config/docker-compose-base.yaml
      service: prometheus

  avalanche:
    extends:
      file: .config/docker-compose-base.yaml
      service: avalanche
