services:
  grafana:
    user: root
    container_name: 'myorg-grafanadynamicsearch-panel'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-12.3.0}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/myorg-grafanadynamicsearch-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/myorg-grafanadynamicsearch-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.myorg-grafanadynamicsearch-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: myorg-grafanadynamicsearch-panel

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml

  avalanche:
    container_name: avalanche
    platform: linux/amd64
    image: quay.io/freshtracks.io/avalanche:latest
    ports:
      - '9001:9001'
